version: "3"

services:

  nginx:
    restart: always
    container_name: xrm-registry-nginx
    image: nginx
    ports:
      - "{{nginx-http}}:80"
      - "{{nginx-https}}:443"
    volumes:
      - {{data-root}}/nginx/conf.d:/etc/nginx/conf.d
      - {{data-root}}/nginx/vhost.d:/etc/nginx/vhost.d
      - {{data-root}}/nginx/html:/usr/share/nginx/html
      - {{data-root}}/nginx/certs:/etc/nginx/certs:ro

  nginx-gen:
    restart: always
    container_name: xrm-registry-nginx-gen
    image: jwilder/docker-gen
    entrypoint: /usr/local/bin/docker-gen -notify-sighup xrm-registry-nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - {{data-root}}/nginx/conf.d:/etc/nginx/conf.d
      - {{data-root}}/nginx/vhost.d:/etc/nginx/vhost.d
      - {{data-root}}/nginx/html:/usr/share/nginx/html
      - {{data-root}}/nginx/certs:/etc/nginx/certs
      - {{data-root}}/nginx/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - nginx

  nginx-letsencrypt:
    restart: always
    container_name: xrm-registry-nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment: 
      - NGINX_DOCKER_GEN_CONTAINER=xrm-registry-nginx-gen
    volumes:
      - {{data-root}}/nginx/conf.d:/etc/nginx/conf.d
      - {{data-root}}/nginx/vhost.d:/etc/nginx/vhost.d
      - {{data-root}}/nginx/html:/usr/share/nginx/html
      - {{data-root}}/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-gen

networks:
  default:
    external:
      name: {{nginx-proxy-network}}